server:
  port: 8772
  profiles:
    active: dev
spring:
  application:
    name: service-task
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:task_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.github.hollykunge.dao: debug
    tk.mybatis: debug

##git创建仓库存放在服务器上的地址
git:
  repository:
    address: C:\\lark_repo\\
    defultMergeBranch: dev