server:
  port: 8772
spring:
  profiles:
    active: dev
  application:
    name: service-task
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.github.hollykunge.dao: debug
    tk.mybatis: debug

##git创建仓库存放在服务器上的地址
git:
  repository:
    address: C:\\lark_repo\\
    defultMergeBranch: dev